import type { Metadata } from "next";
import { inter, robotoMono, monda } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${robotoMono.variable} ${monda.variable}`}
      data-theme="circuit"
    >
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
