name: Python Worker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11' # Match your local environment

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f worker/requirements.txt ]; then pip install -r worker/requirements.txt; fi
        pip install ultralytics requests  # Ensure ultralytics and requests are installed

    - name: Check for model management script
      run: |
        if [ ! -f "worker/download_models.py" ]; then
          echo "❌ Model management script 'worker/download_models.py' not found."
          exit 1
        fi
        echo "✅ Model management script found."

    - name: Test model download (dry run)
      run: |
        cd worker
        python -c "
        import download_models
        print('✅ Model management script can be imported successfully.')
        print('Available models:', list(download_models.MODELS.keys()))
        "

    - name: Download models for CI
      run: python worker/download_models.py

    - name: Check for config file
      run: |
        if [ ! -f "worker/config.py" ]; then
          echo "❌ Config file 'worker/config.py' not found."
          exit 1
        fi
        echo "✅ Config file found."

    - name: Check Python syntax
      run: |
        python -m py_compile worker/production_worker.py
        python -m py_compile worker/download_models.py
        echo "✅ Python syntax OK." 